# Generated by Django 5.0.6 on 2026-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='contact_address',
            field=models.TextField(default='', help_text='Company address'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='contact_email',
            field=models.EmailField(default='', help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='contact_phone',
            field=models.CharField(default='', help_text='Contact phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0, help_text='Number of projects completed'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='total_built_area',
            field=models.CharField(default='', help_text="Total built area (e.g., '500,000+ m²')", max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='who_we_are_image',
            field=models.ImageField(blank=True, help_text='Who We Are section image', null=True, upload_to='who_we_are/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
    ]
